name: mighty_news
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  nb_utils: ^4.3.0+2
  google_fonts: 2.0.0
  http: ^0.13.3
  intl: ^0.17.0
  html: ^0.15.0
  apple_sign_in: ^0.1.0
  url_launcher: ^6.0.2
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  share: ^2.0.1
  onesignal_flutter: ^2.6.3
  package_info: ^2.0.0
  flutter_vlc_player: ^6.0.2
  firebase_core: ^1.1.1
  firebase_auth: ^1.1.4
  firebase_remote_config: ^0.9.0-dev.0
  firebase_crashlytics: ^2.0.3
  google_mobile_ads: ^0.12.1+1
  google_sign_in: ^5.0.2
  flutter_ijkplayer: ^0.3.5+1
  flutter_html: 2.0.0-nullsafety.0
  video_player: ^2.1.1
  cached_network_image: ^3.0.0
  geolocator: ^7.0.3
  flutter_tts: ^3.0.0
  clippy_flutter: ^2.0.0-nullsafety.1
  image_picker: ^0.7.2+1
  flutter_vector_icons: ^1.0.0
  country_code_picker: ^2.0.1
  otp_text_field: ^1.1.0
  photo_view: ^0.11.1
  webview_flutter: ^2.0.9
  
  

  shimmer: ^2.0.0
  fading_edge_scrollview: ^2.0.0

  story_view: ^0.13.0-nullsafety.1

  flutter_localizations:
    sdk: flutter



dev_dependencies:
  flutter_launcher_icons: 
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.2
  mobx_codegen: ^2.0.1+3
  #flutter packages pub run build_runner build --delete-conflicting-outputs


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconx.png"
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/flags/
    - lang/
